let suggestions = [

    "Delhi",
    "Mumbai",
    "Bangalore",
    "Hyderabad",
    "Gujarat",
    "Chennai",
    "Kolkata",
    "Gujarat",
    "Pune",
    "Jaipur, Rajasthan",
    "Lucknow, Uttar Pradesh",
    "Uttar Pradesh,	Kanpur",
    "Maharashtra, Nagpur",
    "Madhya Pradesh, Indore",
    "Maharashtra, Thane",
    "Bhopal	Madhya, Pradesh",
    "Andhra Pradesh, Visakhapatnam",
    "Maharashtra, Pimpri-Chinchwad",
    "Patna, Bihar",
    "Goa",
    "Gujarat, Vadodara",
];
